# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stahes:
  - build
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/
          
testing_testing:
      stage: test
      script: npm test